---

- name: Install the nginx packages 
  apt: name={{ item }} state=present update_cache=yes 
  with_items: 
    - python-selinux
    - nginx

- name: Copy the nginx configuration file 
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: 
   - restart nginx

- name: Copy nginx configuration for sonarqube
  template:
    src: nginx.sonarqubeconf.j2
    dest: /etc/nginx/sites-available/sonarqube.conf

- name: Link nginx configuration for sentry
  file:
    src: /etc/nginx/sites-available/sonarqube.conf
    dest: /etc/nginx/sites-enabled/sonarqube.conf
    state: link
  notify:
    - restart nginx
